---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)

library(assertr)
```

```{r}
weather_one <- read_csv("data/delhi_weather_one.csv")
weather_two <- read_csv("data/delhi_weather_two.csv")
```

```{r}
weather_report <- function(weather){
  
  # Our average temperature, humidity and wind speed 
  weather_means <- 
  weather %>% 
  summarise(
    mean_temp = mean(temp),
    mean_humidity = mean(humidity),
    mean_windspeed = mean(wind_speed)
  )
  
# Show hot and humid days
  hot_and_humid <- 
  weather %>%   
    filter(temp > 20) %>%   
    filter(humidity > 55  )

  return(list(weather_means, hot_and_humid))
}

weather_report(weather_one)
```

This data looks a bit funky 
```{r}
weather_report(weather_two)
```

# Using assertr

```{r}
weather_report <- function(weather){
  
  # do some assertive programming data checks
  # Check that the temperature does not go above or below highest and lowest recorded temperatures. Use numbers which you can justify
  
  weather %>% 
    verify(humidity >= 0 & humidity <= 100) %>% 
    verify(temp >= -35 & temp <= 55) %>% 
    verify(wind_speed >= 0 & wind_speed <= 108) 
  
  
  # Our average temperature, humidity and wind speed 
  weather_means <- 
  weather %>% 
  summarise(
    mean_temp = mean(temp),
    mean_humidity = mean(humidity),
    mean_windspeed = mean(wind_speed)
  )
  
# Show hot and humid days
  hot_and_humid <- 
  weather %>%   
    filter(temp > 20) %>%   
    filter(humidity > 55  )

  return(list(weather_means, hot_and_humid))
}
```

Now we can find weird values. This shows us we have things outwith our verified temperatures in index 15.
```{r}
weather_report(weather_two)
```

## Stop if not (part of BaseR)

```{r}
weather_report <- function(weather){

# If any of these conditions are false, the function will stop  
  stopifnot(
    nrow(weather) > 15,
    ncol(weather) == 4,
    
    # Check for any missing values
    drop_na(weather) == weather
  )
  
  weather %>% 
    verify(temp >= -35 & temp <= 55) %>% 
    verify(wind_speed >= 0 & wind_speed <= 108) %>% 
    verify(humidity >= 0 & humidity <= 100)
  
  # Our average temperature, humidity and wind speed 
  weather_means <- 
  weather %>% 
  summarise(
    mean_temp = mean(temp),
    mean_humidity = mean(humidity),
    mean_windspeed = mean(wind_speed)
  )
  
# Show hot and humid days
hot_and_humid <- 
weather %>% 
  filter(temp > 20) %>% 
  filter(humidity > 55)
return(list(weather_means, hot_and_humid))
}
```


```{r}
weather_report(weather_one)
```

